# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publish.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpublish.proto\"\x16\n\x05\x44\x61tum\x12\r\n\x05\x64\x61tum\x18\x01 \x01(\t\"/\n\x0c\x43onfirmation\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t22\n\x07Publish\x12\'\n\x0cPublishDatum\x12\x06.Datum\x1a\r.Confirmation\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'publish_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATUM']._serialized_start=17
  _globals['_DATUM']._serialized_end=39
  _globals['_CONFIRMATION']._serialized_start=41
  _globals['_CONFIRMATION']._serialized_end=88
  _globals['_PUBLISH']._serialized_start=90
  _globals['_PUBLISH']._serialized_end=140
# @@protoc_insertion_point(module_scope)
