# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import publish_pb2 as publish__pb2


class PublishStub(object):
    """Publish provides mechanisms for talking to various Orcfax publishing
    components.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishDatum = channel.unary_unary(
                '/Publish/PublishDatum',
                request_serializer=publish__pb2.Datum.SerializeToString,
                response_deserializer=publish__pb2.Confirmation.FromString,
                )


class PublishServicer(object):
    """Publish provides mechanisms for talking to various Orcfax publishing
    components.
    """

    def PublishDatum(self, request, context):
        """PublishDatum receives a Datum from a remote host and returns a
        confirmation.

        The confirmation is the value of the datum once parsed. This
        provides a mechanism to understand if what was received is what
        was sent. More secure confirmations are possible.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublishServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishDatum': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishDatum,
                    request_deserializer=publish__pb2.Datum.FromString,
                    response_serializer=publish__pb2.Confirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Publish', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Publish(object):
    """Publish provides mechanisms for talking to various Orcfax publishing
    components.
    """

    @staticmethod
    def PublishDatum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Publish/PublishDatum',
            publish__pb2.Datum.SerializeToString,
            publish__pb2.Confirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
